name: pd_load_state
description: 'Provide UI for various status pages of network data loading, and support responsive switching of UI pages.'
version: 0.1.4
homepage: https://pub.dev/packages/pd_load_state
repository: https://gitee.com/peiduo_734386_admin/pd_load_state/tree/master/

license: MIT

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
