name: pd_load_state
description: Flutter plugin for request load states (loading/error/empty/success) with enhanced UI, multi-platform support and generic data carrying.
version: 0.4.0
homepage: https://gitee.com/pedro-labs/
repository: https://github.com/pedro-pei-me/pd_load_state

license: MIT

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
